### ISSUE TITLE
test a new image with your code 

### ISSUE THREAD

**Issue by dengbingfeng** [untrix/im2latex#13]
I find it not easy to test a new image with your code. So  I use a trick method:

1. fake the test data:

    df = pd.read_pickle('df_test.pkl')
    j = 0 
    for i in range(1,101):
    #for i in range(1,2):
        img_name = "{}.png".format(i) 
        img = cv2.imread('../formula_images/'+img_name,0)
        h,w = img.shape
        while df.iloc[j,8] != 151:
            j += 1        
        df.iloc[j,0] = img_name 
        df.iloc[j,1] = h 
        df.iloc[j,2] = w 
        j += 1
    df.to_pickle('df_test.pkl')

2.then run your test code 
./run.py -a 0.0001 -e -1 -b 28 -v -1 -i 2 --r-lambda 0.00005 --raw-data-folder data/training_56 --restore ./tb_metrics/2018-05-11\ 18-32-56\ CST\ STRIPS/test_runs/step_00168646/ --test --save-all-eval

3.finally , use predict ids in test_*.h5 and id2word in 'data_props.pkl' to get the formula.

I wanna to know if I can do like this and whether there is  a better way I can use ?

**Comment by untrix** [comment]
Hi, Sorry about that. Your solution looks kinda okay, but I'll need to double-check. I'll have some time next week when I intend to do that. I'll probably write instructions or maybe even extend the code to make it easy. Stay tuned.

-Sumeet

**Comment by untrix** [comment]
Hi,

Note: In order to draw predictions from the model you'll first need to train it and save it as a checkpoint/snapshot (the training cycle does this automatically). Then you'll have to execute run.py against the saved snapshot (--restore option) and your inferencing dataset (see below). I hope that you already have a trained model snapshot - otherwise you would be trying to use a randomly initialized model for prediction - which won't work!

Also, I'd appreciate it if you let me know what you are using this for.

For creating the inferencing dataset, I've created a new notebook [src/preprocessing/prepare_inferencing_dataset.ipynb](https://github.com/untrix/im2latex/blob/master/src/preprocessing/prepare_inferencing_dataset.ipynb) that you can use for generating dataset files given a list of images. This notebook replaces the preprocessing_step5_padding.ipynb and writes files to a separate folder suitably named ('inferencing_%d'%batch_size). Follow the notebook and generate the data files in a folder - say inferencing_100. Next, execute run.py using the --test flag and with --raw-data-folder pointing to the abovementioned directory. Also remember to adjust the per-gpu batch-size (-b flag) appropriately e.g.: ./run.py -a 0.0001 -e -1 -b 50 -v -1 -i 2 --r-lambda 0.00005 --raw-data-folder ../data/dataset5/inferencing_100 --test --save-all-eval --restore "./tb_metrics/2017-12-25 21-04-15 PST 140K_noRegroup_score89.09/test_runs/step_00167526_temp"

For extracting the predictions, look at the notebook [src/tools/visualize.ipynb](https://github.com/untrix/im2latex/blob/master/src/tools/visualize.ipynb). You can adjust arguments / variables within the notebook and it gives you everything you need to extract the inferred sequences. Specifically, the function VisualizeDir.strs(...) gives you a dataframe with all predictions etc. You may also look at the file [viz_commons.py](https://github.com/untrix/im2latex/blob/master/src/commons/viz_commons.py) for all the code that this notebook uses.

**Comment by dengbingfeng** [comment]
thanks for your help.   I already have a trained model snapshot, and get almost the same blue as your paper mentioned. 
your inferencing code is pretty good, I use this code to predict a new image and it works well. Thank you!
