### ISSUE TITLE
[Help] Training with existing augmented data files from original torch implementation

### ISSUE THREAD

**Issue by saurabhvyas** [untrix/im2latex#17]
I am trying to figure out a way to train im2latex model in tensorflow, the code which uses torch is a bit outdated, however I have already gone through the augmentation , rendering, preprocessing and filtering.

I have these final files:
formulas.lst
formulas.norm.lst
vocab.txt
final_images/ ( images after all rendering and preprocessing )
train.lst, test.lst and validation.lst ( after running through filtering )

Is there a way to train directly with them ?

Thanks

**Comment by untrix** [comment]
Hi @saurabhvyas 
    I assume that you are referring to the [im2markup model](https://github.com/harvardnlp/im2markup) by the harvard-nlp group. Just so we're clear, [my model](https://untrix.github.io/i2l/) is different from theirs. Hence, if you are trying to train their model in tensorflow, then you'll need to write it first in tensorflow because this repo doesn't reproduce it.

   If you want to train my model however, you will normally need to run through the preprocessing steps first i.e. preprocessing_step_0.ipynb through preprocessing_step_5.ipynb. If you already have formulas.lst, then you can skip step 0 and start with preprocessing_step_1.ipynb - where you can ignore instructions to render the images (since you already have them). Just make sure that you are following the directory structure and naming conventions. Form this point on you need to run all the preprocessing notebooks through preprocessing_step_5.ipynb . These notebooks will also generate the vocabulary and persist a few dataframes and numpy arrays as .pkl files. Therefore sorry, you'll need to go through those steps before you can train using this codebase.

**Comment by saurabhvyas** [comment]
Yes I was referring to im2markup model by Harvard - NLP group, but thanks for clarification and instructions.
